/**
 * AEO Surface Currency Audit
 *
 * Checks the machine-readable, agent-facing discovery surfaces for
 * *currency* — do they still describe what the site actually has — rather
 * than per-page SEO rules (that's scripts/audit-seo.mjs). Three scriptable
 * checks:
 *
 *   1. robots.txt AI-crawler allow-list vs. docs/SEO.md's documented list.
 *   2. openapi.json documented paths vs. the actual files under
 *      public/.well-known/ and public/api/.
 *   3. llms.txt / llms-full.txt Core Sections vs. the real top-level page
 *      slugs in src/middleware.ts's KNOWN_BASE_PATHS.
 *
 * Some AEO checks (content negotiation behavior, FAQPage JSON-LD vs.
 * rendered question count) are not included here — they need a live
 * request or a per-page structural comparison and are recorded manually in
 * analysis_results/AEO_AUDIT.md instead.
 *
 * Usage: node scripts/audit-aeo.mjs [--out <path>]
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const OUT_ARG_IDX = process.argv.indexOf('--out');
const OUT_PATH =
  OUT_ARG_IDX !== -1 && process.argv[OUT_ARG_IDX + 1]
    ? join(ROOT, process.argv[OUT_ARG_IDX + 1])
    : join(ROOT, 'analysis_results', 'AEO_AUDIT_SCRIPTED.md');

function readText(relPath) {
  const p = join(ROOT, relPath);
  return existsSync(p) ? readFileSync(p, 'utf-8') : null;
}

// ── Check 1: robots.txt AI-crawler list vs docs/SEO.md ─────────────────────

function checkCrawlerListCurrency() {
  const robots = readText('public/robots.txt') || '';
  const docs = readText('docs/SEO.md') || '';

  const robotsBots = [
    ...new Set(
      [...robots.matchAll(/^User-agent:\s*([^\s*][^\n]*)/gm)].map((m) =>
        m[1].trim()
      )
    ),
  ].sort();

  const docsListMatch = docs.match(
    /Current AI Crawlers Allowed\s*\n\n([^\n]+)/
  );
  const docsBots = docsListMatch
    ? docsListMatch[1]
        .replace(/\.\s*$/, '')
        .split(',')
        .map((s) => s.trim())
        .sort()
    : [];

  const missingFromDocs = robotsBots.filter((b) => !docsBots.includes(b));
  const missingFromRobots = docsBots.filter((b) => !robotsBots.includes(b));

  return { robotsBots, docsBots, missingFromDocs, missingFromRobots };
}

// ── Check 2: openapi.json paths vs actual .well-known/api files ────────────

function checkOpenApiCoverage() {
  const spec = JSON.parse(readText('public/openapi.json') || '{}');
  const documentedPaths = Object.keys(spec.paths || {});

  const wellKnownDir = join(ROOT, 'public/.well-known');
  const actualWellKnownFiles = [];
  function walk(dir, base = '') {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const rel = base ? `${base}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(join(dir, entry.name), rel);
      } else {
        actualWellKnownFiles.push(`/.well-known/${rel}`);
      }
    }
  }
  if (existsSync(wellKnownDir)) walk(wellKnownDir);

  const documentedSet = new Set(documentedPaths);
  const undocumented = actualWellKnownFiles.filter(
    (f) => !documentedSet.has(f)
  );

  return { documentedPaths, actualWellKnownFiles, undocumented };
}

// ── Check 3: llms.txt Core Sections vs KNOWN_BASE_PATHS ─────────────────────

function checkCoreSectionsCurrency() {
  const middleware = readText('src/middleware.ts') || '';
  const setMatch = middleware.match(
    /const KNOWN_BASE_PATHS = new Set\(\[([\s\S]*?)\]\);/
  );
  const allPaths = setMatch
    ? [...setMatch[1].matchAll(/'([^']*)'/g)].map((m) => m[1])
    : [];
  // Exclude '' (home, always covered) and known redirect-only aliases.
  const REDIRECT_ALIASES = new Set(['setup', 'onboarding', 'docs']);
  const contentSlugs = allPaths.filter(
    (p) => p !== '' && !REDIRECT_ALIASES.has(p)
  );

  const llmsTxt = readText('public/llms.txt') || '';
  const llmsFullTxt = readText('public/llms-full.txt') || '';

  const missingFromLlmsTxt = contentSlugs.filter(
    (slug) => !llmsTxt.includes(`deepworkplan.com/${slug})`)
  );
  const missingFromLlmsFullTxt = contentSlugs.filter(
    (slug) => !llmsFullTxt.includes(`deepworkplan.com/${slug})`)
  );

  return { contentSlugs, missingFromLlmsTxt, missingFromLlmsFullTxt };
}

// ── Main ─────────────────────────────────────────────────────────────────

console.log('🔍 AEO Surface Currency Audit\n');

const crawlers = checkCrawlerListCurrency();
const openapi = checkOpenApiCoverage();
const sections = checkCoreSectionsCurrency();

let report = `# AEO Scripted Checks\n\n`;
report += `Generated by \`scripts/audit-aeo.mjs\`. Complements the manual checks in\n`;
report += `\`AEO_AUDIT.md\` (content negotiation, FAQPage JSON-LD).\n\n`;

report += `## 1. robots.txt AI-crawler list vs. docs/SEO.md\n\n`;
report += `- robots.txt bots: ${crawlers.robotsBots.join(', ')}\n`;
report += `- docs/SEO.md documented bots: ${crawlers.docsBots.join(', ')}\n`;
if (crawlers.missingFromDocs.length > 0) {
  report += `- **warning:** in robots.txt but missing from docs/SEO.md: ${crawlers.missingFromDocs.join(', ')}\n`;
}
if (crawlers.missingFromRobots.length > 0) {
  report += `- **warning:** in docs/SEO.md but missing from robots.txt: ${crawlers.missingFromRobots.join(', ')}\n`;
}
if (
  crawlers.missingFromDocs.length === 0 &&
  crawlers.missingFromRobots.length === 0
) {
  report += `- No mismatch found.\n`;
}
report += `\n`;

report += `## 2. openapi.json coverage of public/.well-known/*\n\n`;
report += `- Actual files under \`public/.well-known/\`: ${openapi.actualWellKnownFiles.length}\n`;
report += `- Documented in openapi.json \`paths\`: ${openapi.documentedPaths.length}\n`;
if (openapi.undocumented.length > 0) {
  report += `- **critical:** real files with zero openapi.json documentation:\n`;
  for (const f of openapi.undocumented) report += `  - \`${f}\`\n`;
} else {
  report += `- No undocumented files found.\n`;
}
report += `\n`;

report += `## 3. llms.txt / llms-full.txt Core Sections vs. KNOWN_BASE_PATHS\n\n`;
report += `- Real content sections (from \`src/middleware.ts\`): ${sections.contentSlugs.join(', ')}\n`;
if (sections.missingFromLlmsTxt.length > 0) {
  report += `- **critical:** missing from \`llms.txt\`: ${sections.missingFromLlmsTxt.join(', ')}\n`;
}
if (sections.missingFromLlmsFullTxt.length > 0) {
  report += `- **critical:** missing from \`llms-full.txt\`: ${sections.missingFromLlmsFullTxt.join(', ')}\n`;
}
if (
  sections.missingFromLlmsTxt.length === 0 &&
  sections.missingFromLlmsFullTxt.length === 0
) {
  report += `- No mismatch found.\n`;
}

writeFileSync(OUT_PATH, report, 'utf-8');

console.log(
  `- robots.txt/docs mismatch: ${crawlers.missingFromDocs.length + crawlers.missingFromRobots.length}`
);
console.log(
  `- openapi.json undocumented .well-known files: ${openapi.undocumented.length}`
);
console.log(
  `- Core Sections missing from llms.txt: ${sections.missingFromLlmsTxt.length}, from llms-full.txt: ${sections.missingFromLlmsFullTxt.length}`
);
console.log(`\n✅ Report written to ${OUT_PATH}\n`);
